// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa37VNVZvK0rP-DGVax6SG7Pg4b-GKxls',
    appId: '1:644801715574:web:6485842e35028e64cc2e57',
    messagingSenderId: '644801715574',
    projectId: 'mini-project-1a7e4',
    authDomain: 'mini-project-1a7e4.firebaseapp.com',
    storageBucket: 'mini-project-1a7e4.appspot.com',
    measurementId: 'G-H4P0T54WPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5v4HJpqIoM_vhBATbECLEN4E8OQOtTsk',
    appId: '1:644801715574:android:fd312c9c4349b702cc2e57',
    messagingSenderId: '644801715574',
    projectId: 'mini-project-1a7e4',
    storageBucket: 'mini-project-1a7e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDos-AdyPaeCwEWSzVVpS_AWw_XVkR0dTY',
    appId: '1:644801715574:ios:580c1eca1ab25a51cc2e57',
    messagingSenderId: '644801715574',
    projectId: 'mini-project-1a7e4',
    storageBucket: 'mini-project-1a7e4.appspot.com',
    iosBundleId: 'com.example.flutterClass24',
  );
}
